repo:
  - ./*
test:
  - src/**/*.test.js

accounts:
   - any: ["src/*/accounts/**/*"]

marketplace:
   - any: ["src/*/marketplace/**/*"]

marketing:
   - any: ["src/*/marketing/**/*"]

zustand:
  - any: ['src/store/*.js']
e2e:
  - any: ['cypress/**/*']

workflow:
  - any: ['.github/**/*']

theme:
  - any: ['src/theme/*.js']
