repo:
  - ./*
test:
  - src/**/*.test.js
middleware:
  - src/middleware.js

accounts:
   - any: ["src/*/accounts/**/*"]

marketplace:
   - any: ["src/*/marketplace/**/*"]

docs:
   - any: ["src/*/docs/**/*"]
cta:
   - any: ["src/*/cta/**/*"]
globals:
   - any: ["src/*/globals/**/*"]

hooks:
   - any: ["src/*/hooks/**/*"]

lib:
   - any: ["src/lib/**/*"]

marketing:
   - any: ["src/*/marketing/**/*"]

zustand:
  - any: ['src/store/*.js']
e2e:
  - any: ['cypress/**/*']

workflow:
  - any: ['.github/**/*']

theme:
  - any: ['src/theme/*.js']
