# Add 'repo' label to any root file changes
repo:
  - ./*

# Add 'test' label to any change to *.spec.js files within the source dir
test:
  - src/**/*.test.js

# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
# source:
#    - any: ["src/**/*", "!src/docs/*"]

# Add 'frontend` label to any change to *.js files as long as the `main.js` hasn't changed
# frontend:
#    - any: ["src/**/*.tsx"]
#      all: ["!src/index.tsx"]

marketplace:
  - any: ['src/pages/marketplace/*.js', 'src/components/marketplace/**/*.js']

accounts:
  - any:
      [
        'src/pages/dashboard/*.js',
        'src/components/accounts/**/*.js',
        'src/pages/instances/*.js',
        'src/pages/profile/*.js',
      ]
e2e:
  - any: ['cypress/**/*']

workflow:
  - any: ['.github/**/*']

theme:
  - any: ['src/theme/*.js']
