name: Zesty Website CI Dev
on:
  push:
    branches: [stage,accounts,production]
  pull_request:
    branches: [stage,accounts,feat/profile]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PRODUCTION: 'false'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Setup custom host for mylocal
        run: echo "127.0.0.1 test.zesty.io" | sudo tee -a /etc/hosts
      - name: Install NPM dependencies build test
        run: npm ci
      - name: Check format and linters
        run: npm run test-all
      - name: Run build
        run: npm run build
      - name: Run test
        run: npm run test
      - name: Write the cypress.env.json file 📝
        run: |
          echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.json
      - name: e2e test
        run: npm run test:e2e:ci

      - name: Save screenshots 🖼
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
